.\"-----------------------------------------------------------------------------
.\" groff -man -Tascii man/ccsvv.1
.\"
.\" \fB .B Bold \fI .I Italic \fR Roman
.\"-----------------------------------------------------------------------------
.TH "CCSVV" "1" "September 2019" "V 0.3" "User Commands"
.\"-----------------------------------------------------------------------------
.SH NAME
ccsvv \- displays a csv (comma separated values) file as a table
.\"-----------------------------------------------------------------------------
.SH SYNOPSIS
.\"-----------------------------------------------------------------------------
.B ccsvv
[\fI\,OPTION\/\fR]... [\fI\,FILE\/\fR]
.\"-----------------------------------------------------------------------------
.SH DESCRIPTION
.\"-----------------------------------------------------------------------------
.PP
The program is called with the name of a csv FILE. If no filename is given, 
ccsvv reads the csv data from stdin.
.\"-----------------------------------------------------------------------------
.TP
\fB\-c\fR, \fB\--checks\fR
By default ccsvv tries to optimize the csv data. It adds missing fields and 
removes empty columns and rows at the end of the table. The flag switches on 
strict checks. A missing field results in an error and no rows or columns are 
removed.
.\"-----------------------------------------------------------------------------
.TP
\fB\-d [\fIdelimiter\fR]\fR, \fB\--delimiter [\fIdelimiter\fR]\fR
Defines a delimiter character, other than the default comma.
.\"-----------------------------------------------------------------------------
.TP
\fB\-h\fR, \fB\--help\fR
Shows a help text.
.\"-----------------------------------------------------------------------------
.TP
\fB\-m\fR, \fB\--monochrom\fR
By default ccsvv uses colors if it is supported by the terminal. With this 
option ccsvv is forced to use a monochrom mode.
.\"-----------------------------------------------------------------------------
.\"
.TP
\fB\-n\fR, \fB\--no-header\fR | \fB\-s\fR, \fB\--show-header\fR
The flags define whether the first row of the table is interpreted as a header 
for the table (\fB\-s\fR) or not (\fB\-n\fR). If none of the flags is given 
ccsvv tries to detect whether a header is present or not.
.\"-----------------------------------------------------------------------------
.TP
\fB\-t\fR, \fB\--trim\fR
Switch off trimming of csv fields.
.\"-----------------------------------------------------------------------------
.SH COMMANDS
After ccsvv was started, the following commands are supported:
.\"-----------------------------------------------------------------------------
.TP
\fB^C\fR, \fB^Q\fR
Terminates the program.
.\"-----------------------------------------------------------------------------
.TP
\fB^H\fR
Shows a help dialog.
.\"-----------------------------------------------------------------------------
.TP
\fB^F\fR
Shows a filter / search dialog.
.\"-----------------------------------------------------------------------------
.TP
\fB^X\fR
Deletes the filter / search string in the dialog.
.\"-----------------------------------------------------------------------------
.TP
\fBESC\fR
Deletes the filter / search string and resets the table.
.\"-----------------------------------------------------------------------------
.TP
\fB^N\fR, \fB^P\fR
Searches for the next (\fB^N\fR) / previous (\fB^P\fR) field that contains the 
filter / search string.
.\"-----------------------------------------------------------------------------
.TP
\fB^S\fR, \fB^R\fR
Sorts the table with the current column in ascending (\fB^S\fR) / descending 
(\fB^R\fR) order.
.\"-----------------------------------------------------------------------------
.SH EXAMPLES
Display the password file with ccsvv:
.PP
.nf
.RS
ccsvv -d : /etc/passwd
.\"-----------------------------------------------------------------------------
.SH SEE ALSO
ncurses(3)
.\"-----------------------------------------------------------------------------
.SH BUGS
No known bugs.
.\"-----------------------------------------------------------------------------
.SH AUTHOR
Dead End

